server:
  port: 8087

spring:
  application:
    name: notification-service
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:11026}
      password: ${SPRING_REDIS_PASSWORD:}

notifications:
  channel: ${NOTIFICATIONS_CHANNEL:notifications}
  sse-timeout-ms: ${NOTIFICATIONS_SSE_TIMEOUT_MS:3600000}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:11024/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
