server:
  port: 8083

spring:
  application:
    name: forum-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:11022/mtg_forum}
      auto-index-creation: true
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:11026}
      password: ${SPRING_REDIS_PASSWORD:}

notifications:
  channel: ${NOTIFICATIONS_CHANNEL:notifications}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:11024/eureka-mtgc/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
